// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserId   string `json:"userid"`
	Password string `json:"password"`
}

type LoginResp struct {
	Staus int64  `json:"status"`
	Msg   string `json:"msg"`
}
